### ISSUE TITLE
Add Union node to Elyra NLP Canvas

### ISSUE THREAD

**Issue by zeusorionIBM** [elyra-ai/nlp-editor#3]
**Description:**
Add functionality to allow a user to combine extractors in a union when generating NLP rules. More information on a union can be found [here](https://cloud.ibm.com/docs/watson-knowledge-studio?topic=watson-knowledge-studio-managing-projects-and-extractors#creating-a-union).

**Tasks:**
- [x] add a union node to the palette
- [x] render any relevant properties and controls requesting user input on the right pane
- [x] validate that all required input from the user is entered and correct
- [x] transform user's input into payload that SystemT can then translate and run as AQL.
